// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockly.Msg.zh.hant');

goog.require('Blockly.Msg');

Blockly.Msg.ADD_COMMENT = "加入註解";
Blockly.Msg.AUTH = "請授權這個應用程式以保存您的作品並共享。";
Blockly.Msg.CHANGE_VALUE_TITLE = "修改值:";
Blockly.Msg.CHAT = "與您的合作者洽談藉由在此框輸入！";
Blockly.Msg.CLEAN_UP = "清理積木";
Blockly.Msg.COLLAPSE_ALL = "收合積木";
Blockly.Msg.COLLAPSE_BLOCK = "收合積木";
Blockly.Msg.COLOUR_BLEND_COLOUR1 = "顏色 1";
Blockly.Msg.COLOUR_BLEND_COLOUR2 = "顏色 2";
Blockly.Msg.COLOUR_BLEND_HELPURL = "http://meyerweb.com/eric/tools/color-blend/";  // untranslated
Blockly.Msg.COLOUR_BLEND_RATIO = "比例";
Blockly.Msg.COLOUR_BLEND_TITLE = "混合";
Blockly.Msg.COLOUR_BLEND_TOOLTIP = "透過比率 (0.0-1.0)來混合兩種顏色。";
Blockly.Msg.COLOUR_PICKER_HELPURL = "https://zh.wikipedia.org/wiki/顏色";
Blockly.Msg.COLOUR_PICKER_TOOLTIP = "從調色板中選擇一種顏色。";
Blockly.Msg.COLOUR_RANDOM_HELPURL = "http://randomcolour.com";  // untranslated
Blockly.Msg.COLOUR_RANDOM_TITLE = "隨機顏色";
Blockly.Msg.COLOUR_RANDOM_TOOLTIP = "隨機選擇一種顏色。";
Blockly.Msg.COLOUR_RGB_BLUE = "藍";
Blockly.Msg.COLOUR_RGB_GREEN = "綠";
Blockly.Msg.COLOUR_RGB_HELPURL = "http://www.december.com/html/spec/colorper.html";  // untranslated
Blockly.Msg.COLOUR_RGB_RED = "紅";
Blockly.Msg.COLOUR_RGB_TITLE = "顏色";
Blockly.Msg.COLOUR_RGB_TOOLTIP = "透過指定紅、綠、 藍色的值來建立顏色。所有的值必須介於 0 和 100 之間。";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_HELPURL = "https://github.com/google/blockly/wiki/Loops#loop-termination-blocks";  // untranslated
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK = "跳出 迴圈";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE = "繼續下一次 迴圈";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK = "跳出目前的 迴圈";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE = "跳過迴圈的其餘步驟，馬上繼續執行下一次迴圈。";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_WARNING = "警告： 此積木僅可使用在迴圈內。";
Blockly.Msg.CONTROLS_FOREACH_HELPURL = "https://github.com/google/blockly/wiki/Loops#for-each";  // untranslated
Blockly.Msg.CONTROLS_FOREACH_TITLE = "取出每個 %1 從清單 %2";
Blockly.Msg.CONTROLS_FOREACH_TOOLTIP = "走訪清單中的每一個項目，將增量  '%1' 設定到該項目中，然後執行區塊的積木。";
Blockly.Msg.CONTROLS_FOR_HELPURL = "https://github.com/google/blockly/wiki/Loops#count-with";  // untranslated
Blockly.Msg.CONTROLS_FOR_TITLE = "使用 %1 從範圍 %2 到 %3 每隔 %4";
Blockly.Msg.CONTROLS_FOR_TOOLTIP = "從起始數到結尾數依序取出變數 \"%1\" 的值，按指定間隔，執行區塊的積木。";
Blockly.Msg.CONTROLS_IF_ELSEIF_TOOLTIP = "新增條件區塊到'如果'積木中。";
Blockly.Msg.CONTROLS_IF_ELSE_TOOLTIP = "新增最後其他條件區塊到'如果'積木中。";
Blockly.Msg.CONTROLS_IF_HELPURL = "https://github.com/google/blockly/wiki/IfElse";  // untranslated
Blockly.Msg.CONTROLS_IF_IF_TOOLTIP = "新增、 刪除或重新排列區塊來配置'如果'積木。";
Blockly.Msg.CONTROLS_IF_MSG_ELSE = "否則";
Blockly.Msg.CONTROLS_IF_MSG_ELSEIF = "否則如果";
Blockly.Msg.CONTROLS_IF_MSG_IF = "如果";
Blockly.Msg.CONTROLS_IF_TOOLTIP_1 = "當值為真時，執行區塊的積木";
Blockly.Msg.CONTROLS_IF_TOOLTIP_2 = "當值為真時，執行第一個區塊的積木，否則則執行第二個區塊的積木";
Blockly.Msg.CONTROLS_IF_TOOLTIP_3 = "如果第一個值為真，則執行第一個區塊的積木。否則當第二個值為真時，則執行第二個區塊的積木";
Blockly.Msg.CONTROLS_IF_TOOLTIP_4 = "如果第一個值為真，則執行第一個區塊的積木。否則當第二個值為真時，則執行第二個區塊的積木。如果前幾個敘述都不為真，則執行最後一個區塊的積木";
Blockly.Msg.CONTROLS_REPEAT_HELPURL = "https://zh.wikipedia.org/wiki/For迴圈";
Blockly.Msg.CONTROLS_REPEAT_INPUT_DO = "執行";
Blockly.Msg.CONTROLS_REPEAT_TITLE = "重複 %1 次";
Blockly.Msg.CONTROLS_REPEAT_TOOLTIP = "多次重複執行區塊的積木";
Blockly.Msg.CONTROLS_WHILEUNTIL_HELPURL = "https://github.com/google/blockly/wiki/Loops#repeat";  // untranslated
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_UNTIL = "重複 直到";
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_WHILE = "重複 當";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL = "當值為否時，執行區塊的積木";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_WHILE = "當值為真時，執行區塊的積木";
Blockly.Msg.DELETE_ALL_BLOCKS = "刪除共 %1 塊積木？";
Blockly.Msg.DELETE_BLOCK = "刪除積木";
Blockly.Msg.DELETE_X_BLOCKS = "刪除 %1 塊積木";
Blockly.Msg.DISABLE_BLOCK = "停用積木";
Blockly.Msg.DUPLICATE_BLOCK = "複製";
Blockly.Msg.ENABLE_BLOCK = "啟用積木";
Blockly.Msg.EXPAND_ALL = "展開全部積木";
Blockly.Msg.EXPAND_BLOCK = "展開積木";
Blockly.Msg.EXTERNAL_INPUTS = "多行輸入";
Blockly.Msg.HELP = "說明";
Blockly.Msg.INLINE_INPUTS = "單行輸入";
Blockly.Msg.LISTS_CREATE_EMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-empty-list";  // untranslated
Blockly.Msg.LISTS_CREATE_EMPTY_TITLE = "建立空清單";
Blockly.Msg.LISTS_CREATE_EMPTY_TOOLTIP = "建立長度 0 的清單，不包含任何項目";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TITLE_ADD = "新增";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TOOLTIP = "新增、 刪除或重新排列各區塊來此重新配置這個 清單 積木。";
Blockly.Msg.LISTS_CREATE_WITH_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
Blockly.Msg.LISTS_CREATE_WITH_INPUT_WITH = "使用這些項目建立清單";
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TOOLTIP = "將一個項目加入到清單中。";
Blockly.Msg.LISTS_CREATE_WITH_TOOLTIP = "建立一個擁有任意數量項目的清單。";
Blockly.Msg.LISTS_GET_INDEX_FIRST = "第一筆";
Blockly.Msg.LISTS_GET_INDEX_FROM_END = "倒數第#筆";
Blockly.Msg.LISTS_GET_INDEX_FROM_START = "#";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_GET = "取值";
Blockly.Msg.LISTS_GET_INDEX_GET_REMOVE = "取出並移除";
Blockly.Msg.LISTS_GET_INDEX_LAST = "最後一筆";
Blockly.Msg.LISTS_GET_INDEX_RANDOM = "隨機";
Blockly.Msg.LISTS_GET_INDEX_REMOVE = "移除";
Blockly.Msg.LISTS_GET_INDEX_TAIL = "";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FIRST = "返回清單中的第一個項目";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_END = "返回在清單中的指定位置的項目。#1 是最後一個項目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_START = "返回在清單中的指定位置的項目。#1 是第一個項目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_LAST = "返回清單中的最後一個項目";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_RANDOM = "返回清單中隨機的一個項目";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST = "移除並返回清單中的第一個項目";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_END = "移除並返回清單中的指定位置的項目。#1 是最後一個項目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_START = "移除並返回清單中的指定位置的項目。#1 是第一個項目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST = "移除並返回清單中的最後一個項目";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM = "移除並返回清單中的隨機一個項目";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST = "移除清單中的第一個項目";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_END = "移除在清單中的指定位置的項目。#1 是最後一個項目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_START = "移除在清單中的指定位置的項目。#1 是第一個項目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST = "移除清單中的最後一個項目";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM = "移除清單中隨機的一個項目";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_END = "到 倒數 # 位";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_START = "到 #";
Blockly.Msg.LISTS_GET_SUBLIST_END_LAST = "到 最後";
Blockly.Msg.LISTS_GET_SUBLIST_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-a-sublist";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_START_FIRST = "從 頭 開始";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_END = "從倒數 # 開始";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_START = "從 # 開始";
Blockly.Msg.LISTS_GET_SUBLIST_TAIL = "";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_TOOLTIP = "複製清單中指定的部分。";
Blockly.Msg.LISTS_INDEX_OF_FIRST = "找出 第一個 出現項目";
Blockly.Msg.LISTS_INDEX_OF_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-items-from-a-list";  // untranslated
Blockly.Msg.LISTS_INDEX_OF_LAST = "找出 最後一個 出現的項目";
Blockly.Msg.LISTS_INDEX_OF_TOOLTIP = "傳回清單中第一個/最後一個符合項目的索引值。如果沒有找到傳回 %1。";
Blockly.Msg.LISTS_INLIST = "在清單";
Blockly.Msg.LISTS_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#is-empty";  // untranslated
Blockly.Msg.LISTS_ISEMPTY_TITLE = "%1 值為空清單";
Blockly.Msg.LISTS_ISEMPTY_TOOLTIP = "如果該清單為空清單，則傳回 真。";
Blockly.Msg.LISTS_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Lists#length-of";  // untranslated
Blockly.Msg.LISTS_LENGTH_TITLE = "清單長度 %1";
Blockly.Msg.LISTS_LENGTH_TOOLTIP = "傳回清單長度。";
Blockly.Msg.LISTS_REPEAT_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
Blockly.Msg.LISTS_REPEAT_TITLE = "建立清單使用項目 %1 重複 %2 次";
Blockly.Msg.LISTS_REPEAT_TOOLTIP = "建立包含指定重複次數的 值 的清單。";
Blockly.Msg.LISTS_SET_INDEX_HELPURL = "https://github.com/google/blockly/wiki/Lists#in-list--set";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_INPUT_TO = "為";
Blockly.Msg.LISTS_SET_INDEX_INSERT = "插入在";
Blockly.Msg.LISTS_SET_INDEX_SET = "指定";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST = "在清單的起始處添加一個項目";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_END = "插入在清單中的指定位置的項目。#1 是最後一個項目。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_START = "插入在清單中的指定位置的項目。#1 是第一個項目。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_LAST = "在清單的尾端加入一個項目";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM = "在清單中隨機插入項目";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FIRST = "設定清單中的第一個項目";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_END = "設定在清單中的指定位置的項目。#1 是最後一個項目。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_START = "設定在清單中的指定位置的項目。#1 是第一個項目。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_LAST = "設定清單中的最後一個項目";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_RANDOM = "設定清單中隨機的一個項目";
Blockly.Msg.LISTS_SORT_HELPURL = "https://github.com/google/blockly/wiki/Lists#sorting-a-list";
Blockly.Msg.LISTS_SORT_ORDER_ASCENDING = "遞增";
Blockly.Msg.LISTS_SORT_ORDER_DESCENDING = "遞減";
Blockly.Msg.LISTS_SORT_TITLE = "清單依%1%2%3進行排序";
Blockly.Msg.LISTS_SORT_TOOLTIP = "排序清單的項目";
Blockly.Msg.LISTS_SORT_TYPE_IGNORECASE = "字母並忽略大小寫";
Blockly.Msg.LISTS_SORT_TYPE_NUMERIC = "數字";
Blockly.Msg.LISTS_SORT_TYPE_TEXT = "字母";
Blockly.Msg.LISTS_SPLIT_HELPURL = "https://github.com/google/blockly/wiki/Lists#splitting-strings-and-joining-lists";  // untranslated
Blockly.Msg.LISTS_SPLIT_LIST_FROM_TEXT = "從字串分割建立清單";
Blockly.Msg.LISTS_SPLIT_TEXT_FROM_LIST = "從清單合併建立字串";
Blockly.Msg.LISTS_SPLIT_TOOLTIP_JOIN = "連接清單項目成為一個字串，並且使用分隔符號分隔。";
Blockly.Msg.LISTS_SPLIT_TOOLTIP_SPLIT = "分割字串成為一個清單，使用分隔符號來分割成項目。";
Blockly.Msg.LISTS_SPLIT_WITH_DELIMITER = "使用分隔符號";
Blockly.Msg.LOGIC_BOOLEAN_FALSE = "否";
Blockly.Msg.LOGIC_BOOLEAN_HELPURL = "https://github.com/google/blockly/wiki/Logic#values";  // untranslated
Blockly.Msg.LOGIC_BOOLEAN_TOOLTIP = "傳回 真 或 否。";
Blockly.Msg.LOGIC_BOOLEAN_TRUE = "真";
Blockly.Msg.LOGIC_COMPARE_HELPURL = "https://zh.wikipedia.org/wiki/不等";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_EQ = "如果這兩個輸入區塊內容相等，傳回 真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GT = "如果第一個輸入大於第二個輸入，傳回 真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GTE = "如果第一個輸入大於或等於第二個輸入，傳回 真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LT = "如果第一個輸入小於第二個輸入，傳回 真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LTE = "如果第一個輸入是小於或等於第二個輸入，傳回 真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_NEQ = "如果這兩個輸入區塊內容不相等，傳回 真。";
Blockly.Msg.LOGIC_NEGATE_HELPURL = "https://github.com/google/blockly/wiki/Logic#not";  // untranslated
Blockly.Msg.LOGIC_NEGATE_TITLE = "非 %1";
Blockly.Msg.LOGIC_NEGATE_TOOLTIP = "如果輸入的值是 否，則傳回 真。如果輸入的值是 真 傳回 否。";
Blockly.Msg.LOGIC_NULL = "空值";
Blockly.Msg.LOGIC_NULL_HELPURL = "https://en.wikipedia.org/wiki/Nullable_type";  // untranslated
Blockly.Msg.LOGIC_NULL_TOOLTIP = "傳回 空值。";
Blockly.Msg.LOGIC_OPERATION_AND = "且";
Blockly.Msg.LOGIC_OPERATION_HELPURL = "https://github.com/google/blockly/wiki/Logic#logical-operations";  // untranslated
Blockly.Msg.LOGIC_OPERATION_OR = "或";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_AND = "如果這兩個輸入值都為 真，則傳回 真。";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_OR = "如果至少一個輸入的值為 真，傳回 真。";
Blockly.Msg.LOGIC_TERNARY_CONDITION = "測試";
Blockly.Msg.LOGIC_TERNARY_HELPURL = "https://zh.wikipedia.org/wiki/條件運算符";
Blockly.Msg.LOGIC_TERNARY_IF_FALSE = "如果為否";
Blockly.Msg.LOGIC_TERNARY_IF_TRUE = "如果為真";
Blockly.Msg.LOGIC_TERNARY_TOOLTIP = "檢查 '測試' 條件。如果條件為 真，將傳回 '如果為 真' 值 ；否則，傳回 '如果為 否' 的值。";
Blockly.Msg.MATH_ADDITION_SYMBOL = "+";  // untranslated
Blockly.Msg.MATH_ARITHMETIC_HELPURL = "https://en.wikipedia.org/wiki/Arithmetic";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_ADD = "傳回兩個數字的總和。";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_DIVIDE = "傳回兩個數字的商。";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MINUS = "傳回兩個數字的差。";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MULTIPLY = "傳回兩個數字的乘積。";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_POWER = "傳回第二個數字是第一個數字為底的指數。";
Blockly.Msg.MATH_CHANGE_HELPURL = "https://zh.wikipedia.org/wiki/加法";
Blockly.Msg.MATH_CHANGE_TITLE = "更改 %1 變數值增加 %2";
Blockly.Msg.MATH_CHANGE_TOOLTIP = "將數字增加到變數 '%1'。";
Blockly.Msg.MATH_CONSTANT_HELPURL = "https://zh.wikipedia.org/wiki/數學常數";
Blockly.Msg.MATH_CONSTANT_TOOLTIP = "傳回一個數學常數： π (3.141......)，e (2.718...)、 φ (1.618...)、 開方(2) (1.414......)、 開方(½) (0.707......) 或 ∞ （無窮大）。";
Blockly.Msg.MATH_CONSTRAIN_HELPURL = "https://en.wikipedia.org/wiki/Clamping_%28graphics%29";  // untranslated
Blockly.Msg.MATH_CONSTRAIN_TITLE = "限制數字 %1 介於 (最小) %2 到 (最大) %3";
Blockly.Msg.MATH_CONSTRAIN_TOOLTIP = "限制數字介於兩個指定數字之間";
Blockly.Msg.MATH_DIVISION_SYMBOL = "÷";  // untranslated
Blockly.Msg.MATH_IS_DIVISIBLE_BY = "可被整除";
Blockly.Msg.MATH_IS_EVEN = "是偶數";
Blockly.Msg.MATH_IS_NEGATIVE = "是負值";
Blockly.Msg.MATH_IS_ODD = "是奇數";
Blockly.Msg.MATH_IS_POSITIVE = "是正值";
Blockly.Msg.MATH_IS_PRIME = "是質數";
Blockly.Msg.MATH_IS_TOOLTIP = "如果數字是偶數，奇數，非負整數，正數、 負數或是可被某數字整除，則傳回 真 或 否。";
Blockly.Msg.MATH_IS_WHOLE = "是非負整數";
Blockly.Msg.MATH_MODULO_HELPURL = "https://zh.wikipedia.org/wiki/模除";
Blockly.Msg.MATH_MODULO_TITLE = "餘數: %1 ÷ %2";
Blockly.Msg.MATH_MODULO_TOOLTIP = "傳回兩個數字相除的餘數";
Blockly.Msg.MATH_MULTIPLICATION_SYMBOL = "×";  // untranslated
Blockly.Msg.MATH_NUMBER_HELPURL = "https://zh.wikipedia.org/wiki/數";
Blockly.Msg.MATH_NUMBER_TOOLTIP = "一個數字。";
Blockly.Msg.MATH_ONLIST_HELPURL = "";  // untranslated
Blockly.Msg.MATH_ONLIST_OPERATOR_AVERAGE = "清單的平均值";
Blockly.Msg.MATH_ONLIST_OPERATOR_MAX = "清單的最大值";
Blockly.Msg.MATH_ONLIST_OPERATOR_MEDIAN = "清單的中位數";
Blockly.Msg.MATH_ONLIST_OPERATOR_MIN = "清單的最小值";
Blockly.Msg.MATH_ONLIST_OPERATOR_MODE = "清單的最常出現";
Blockly.Msg.MATH_ONLIST_OPERATOR_RANDOM = "清單的隨機抽取";
Blockly.Msg.MATH_ONLIST_OPERATOR_STD_DEV = "清單的標準差";
Blockly.Msg.MATH_ONLIST_OPERATOR_SUM = "清單的總和";
Blockly.Msg.MATH_ONLIST_TOOLTIP_AVERAGE = "傳回清單數值的平均值 （算術平均值）。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MAX = "傳回清單的最大數字。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MEDIAN = "傳回清單數值的中位數。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MIN = "傳回清單的最小數字。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MODE = "傳回清單最常出現項目。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_RANDOM = "從清單傳回一個隨機項目。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_STD_DEV = "傳回清單數字的標準差。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_SUM = "傳回清單所有數字的總和。";
Blockly.Msg.MATH_POWER_SYMBOL = "^";  // untranslated
Blockly.Msg.MATH_RANDOM_FLOAT_HELPURL = "https://en.wikipedia.org/wiki/Random_number_generation";
Blockly.Msg.MATH_RANDOM_FLOAT_TITLE_RANDOM = "傳回隨機數";
Blockly.Msg.MATH_RANDOM_FLOAT_TOOLTIP = "傳回介於 （包含） 0.0 到 1.0 之間的隨機數。";
Blockly.Msg.MATH_RANDOM_INT_HELPURL = "https://zh.wikipedia.org/wiki/隨機數生成器";
Blockly.Msg.MATH_RANDOM_INT_TITLE = "傳回隨機整數介於 (最小) %1 到 (最大) %2";
Blockly.Msg.MATH_RANDOM_INT_TOOLTIP = "傳回限制數字區間內的隨機數字";
Blockly.Msg.MATH_ROUND_HELPURL = "https://zh.wikipedia.org/wiki/數值簡化";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUND = "四捨五入";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDDOWN = "無條件捨去";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDUP = "無條件進位";
Blockly.Msg.MATH_ROUND_TOOLTIP = "將數字向上或向下捨入。";
Blockly.Msg.MATH_SINGLE_HELPURL = "https://zh.wikipedia.org/wiki/平方根";
Blockly.Msg.MATH_SINGLE_OP_ABSOLUTE = "絕對值";
Blockly.Msg.MATH_SINGLE_OP_ROOT = "開根號";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ABS = "傳回指定數字的絕對值。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_EXP = "傳回指定數字的e指數 ";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LN = "傳回指定數字的自然對數。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LOG10 = "傳回指定數字的對數。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_NEG = "傳回指定數字的 negation。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_POW10 = "傳回指定數字指數的10的冪次。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ROOT = "傳回指定數字的平方根。";
Blockly.Msg.MATH_SUBTRACTION_SYMBOL = "-";  // untranslated
Blockly.Msg.MATH_TRIG_ACOS = "acos";  // untranslated
Blockly.Msg.MATH_TRIG_ASIN = "asin";  // untranslated
Blockly.Msg.MATH_TRIG_ATAN = "atan";  // untranslated
Blockly.Msg.MATH_TRIG_COS = "cos";  // untranslated
Blockly.Msg.MATH_TRIG_HELPURL = "https://zh.wikipedia.org/wiki/三角函數";
Blockly.Msg.MATH_TRIG_SIN = "sin";  // untranslated
Blockly.Msg.MATH_TRIG_TAN = "tan";  // untranslated
Blockly.Msg.MATH_TRIG_TOOLTIP_ACOS = "傳回指定角度的反餘弦值(非弧度）。";
Blockly.Msg.MATH_TRIG_TOOLTIP_ASIN = "傳回指定角度的反正弦值(非弧度）。";
Blockly.Msg.MATH_TRIG_TOOLTIP_ATAN = "傳回指定角度的反正切值。";
Blockly.Msg.MATH_TRIG_TOOLTIP_COS = "傳回指定角度的餘弦值(非弧度）。";
Blockly.Msg.MATH_TRIG_TOOLTIP_SIN = "傳回指定角度的正弦值(非弧度）。";
Blockly.Msg.MATH_TRIG_TOOLTIP_TAN = "傳回指定角度的正切值(非弧度）。";
Blockly.Msg.ME = "我";
Blockly.Msg.NEW_VARIABLE = "建立變數...";
Blockly.Msg.NEW_VARIABLE_TITLE = "新變數名稱:";
Blockly.Msg.ORDINAL_NUMBER_SUFFIX = "";  // untranslated
Blockly.Msg.PROCEDURES_ALLOW_STATEMENTS = "擁有積木區塊";
Blockly.Msg.PROCEDURES_BEFORE_PARAMS = "參數：";
Blockly.Msg.PROCEDURES_CALLNORETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";
Blockly.Msg.PROCEDURES_CALLNORETURN_TOOLTIP = "執行使用者定義的函數 '%1'。";
Blockly.Msg.PROCEDURES_CALLRETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";
Blockly.Msg.PROCEDURES_CALLRETURN_TOOLTIP = "執行使用者定義函數 '%1' 並使用回傳值";
Blockly.Msg.PROCEDURES_CALL_BEFORE_PARAMS = "參數：";
Blockly.Msg.PROCEDURES_CREATE_DO = "建立 '%1'";
Blockly.Msg.PROCEDURES_DEFNORETURN_COMMENT = "描述此函數...";
Blockly.Msg.PROCEDURES_DEFNORETURN_DO = "";  // untranslated
Blockly.Msg.PROCEDURES_DEFNORETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";  // untranslated
Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE = "sub";
Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE = "定義";
Blockly.Msg.PROCEDURES_DEFNORETURN_TOOLTIP = "建立一個沒有回傳值的函數。";
Blockly.Msg.PROCEDURES_DEFRETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";  // untranslated
Blockly.Msg.PROCEDURES_DEFRETURN_RETURN = "回傳";
Blockly.Msg.PROCEDURES_DEFRETURN_TOOLTIP = "建立一個有回傳值的函數。";
Blockly.Msg.PROCEDURES_DEF_DUPLICATE_WARNING = "警告: 此函數中有重複參數。";
Blockly.Msg.PROCEDURES_HIGHLIGHT_DEF = "反白顯示函數定義";
Blockly.Msg.PROCEDURES_IFRETURN_HELPURL = "http://c2.com/cgi/wiki?GuardClause";  // untranslated
Blockly.Msg.PROCEDURES_IFRETURN_TOOLTIP = "如果值為 真，則傳回第二個值。";
Blockly.Msg.PROCEDURES_IFRETURN_WARNING = "警告: 此積木僅可在定義函數時使用。";
Blockly.Msg.PROCEDURES_MUTATORARG_TITLE = "變數:";
Blockly.Msg.PROCEDURES_MUTATORARG_TOOLTIP = "新增函數輸入。";
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TITLE = "參數";
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TOOLTIP = "新增、刪除或重新排列此函數的輸入。";
Blockly.Msg.REDO = "重試";
Blockly.Msg.REMOVE_COMMENT = "移除註解";
Blockly.Msg.RENAME_VARIABLE = "重新命名變數...";
Blockly.Msg.RENAME_VARIABLE_TITLE = "將所有 \"%1\" 變數重新命名為:";
Blockly.Msg.TEXT_APPEND_APPENDTEXT = "後加入字串";
Blockly.Msg.TEXT_APPEND_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg.TEXT_APPEND_TO = "在變數";
Blockly.Msg.TEXT_APPEND_TOOLTIP = "將一些字串新增到變數 '%1'。";
Blockly.Msg.TEXT_CHANGECASE_HELPURL = "https://github.com/google/blockly/wiki/Text#adjusting-text-case";  // untranslated
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_LOWERCASE = "轉成 小寫";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_TITLECASE = "轉成 字首大寫";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_UPPERCASE = "轉成 大寫";
Blockly.Msg.TEXT_CHANGECASE_TOOLTIP = "使用不同的大小寫複製這段文字。";
Blockly.Msg.TEXT_CHARAT_FIRST = "取第一個字元";
Blockly.Msg.TEXT_CHARAT_FROM_END = "取得 倒數第 # 個字元";
Blockly.Msg.TEXT_CHARAT_FROM_START = "取得 字元 #";
Blockly.Msg.TEXT_CHARAT_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-text";  // untranslated
Blockly.Msg.TEXT_CHARAT_INPUT_INTEXT = "從字串";
Blockly.Msg.TEXT_CHARAT_LAST = "取最後一個字元";
Blockly.Msg.TEXT_CHARAT_RANDOM = "取隨機一個字元";
Blockly.Msg.TEXT_CHARAT_TAIL = "";
Blockly.Msg.TEXT_CHARAT_TOOLTIP = "傳回位於指定位置的字元。";
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TOOLTIP = "將一個項目加入到字串中。";
Blockly.Msg.TEXT_CREATE_JOIN_TITLE_JOIN = "加入";
Blockly.Msg.TEXT_CREATE_JOIN_TOOLTIP = "新增、 刪除或重新排列各區塊來此重新配置這個字串積木。";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_END = "到 倒數第 # 個字元";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_START = "到 字元 #";
Blockly.Msg.TEXT_GET_SUBSTRING_END_LAST = "到 最後一個字元";
Blockly.Msg.TEXT_GET_SUBSTRING_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-a-region-of-text";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_INPUT_IN_TEXT = "從字串";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FIRST = "取得子字串 從 第一個字元";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_END = "取得子字串從 #";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_START = "取得子字串從 #";
Blockly.Msg.TEXT_GET_SUBSTRING_TAIL = "";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_TOOLTIP = "傳回部分子字串。";
Blockly.Msg.TEXT_INDEXOF_HELPURL = "https://github.com/google/blockly/wiki/Text#finding-text";  // untranslated
Blockly.Msg.TEXT_INDEXOF_INPUT_INTEXT = "從字串";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_FIRST = "尋找 第一個 出現的字串";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_LAST = "尋找 最後一個 出現的字串";
Blockly.Msg.TEXT_INDEXOF_TAIL = "";  // untranslated
Blockly.Msg.TEXT_INDEXOF_TOOLTIP = "傳回在第二個字串中第一個/最後一個符合項目的索引值。如果沒有找到傳回 %1。";
Blockly.Msg.TEXT_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Text#checking-for-empty-text";  // untranslated
Blockly.Msg.TEXT_ISEMPTY_TITLE = "%1 為空字串";
Blockly.Msg.TEXT_ISEMPTY_TOOLTIP = "如果提供的字串為空字串，則傳回 真。";
Blockly.Msg.TEXT_JOIN_HELPURL = "https://github.com/google/blockly/wiki/Text#text-creation";  // untranslated
Blockly.Msg.TEXT_JOIN_TITLE_CREATEWITH = "合併字串使用";
Blockly.Msg.TEXT_JOIN_TOOLTIP = "合併連接任意數量項目來建立字串。";
Blockly.Msg.TEXT_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg.TEXT_LENGTH_TITLE = "長度 %1";
Blockly.Msg.TEXT_LENGTH_TOOLTIP = "傳回字串的字元數（含空格） 。";
Blockly.Msg.TEXT_PRINT_HELPURL = "https://github.com/google/blockly/wiki/Text#printing-text";  // untranslated
Blockly.Msg.TEXT_PRINT_TITLE = "輸出 %1";
Blockly.Msg.TEXT_PRINT_TOOLTIP = "輸出指定字串、 數字或其他值。";
Blockly.Msg.TEXT_PROMPT_HELPURL = "https://github.com/google/blockly/wiki/Text#getting-input-from-the-user";  // untranslated
Blockly.Msg.TEXT_PROMPT_TOOLTIP_NUMBER = "輸入數字";
Blockly.Msg.TEXT_PROMPT_TOOLTIP_TEXT = "輸入字串";
Blockly.Msg.TEXT_PROMPT_TYPE_NUMBER = "輸入 數字 並顯示提示訊息";
Blockly.Msg.TEXT_PROMPT_TYPE_TEXT = "輸入 字串 並顯示提示訊息";
Blockly.Msg.TEXT_TEXT_HELPURL = "https://zh.wikipedia.org/wiki/字串";
Blockly.Msg.TEXT_TEXT_TOOLTIP = "字元、 單詞或一行文字。";
Blockly.Msg.TEXT_TRIM_HELPURL = "https://github.com/google/blockly/wiki/Text#trimming-removing-spaces";  // untranslated
Blockly.Msg.TEXT_TRIM_OPERATOR_BOTH = "消除兩側空白字元";
Blockly.Msg.TEXT_TRIM_OPERATOR_LEFT = "消除左側空白字元";
Blockly.Msg.TEXT_TRIM_OPERATOR_RIGHT = "消除右側空白字元";
Blockly.Msg.TEXT_TRIM_TOOLTIP = "複製字串的同時刪除兩端多餘的空白字元。";
Blockly.Msg.TODAY = "今天";
Blockly.Msg.UNDO = "復原";
Blockly.Msg.VARIABLES_DEFAULT_NAME = "var1";
Blockly.Msg.VARIABLES_GET_CREATE_SET = "建立 '設定 %1'";
Blockly.Msg.VARIABLES_GET_HELPURL = "https://github.com/google/blockly/wiki/Variables#get";  // untranslated
Blockly.Msg.VARIABLES_GET_TOOLTIP = "傳回此變數的值。";
Blockly.Msg.VARIABLES_SET = "指定 %1 變數值成為 %2";
Blockly.Msg.VARIABLES_SET_CREATE_GET = "建立 '取得 %1'";
Blockly.Msg.VARIABLES_SET_HELPURL = "https://github.com/google/blockly/wiki/Variables#set";  // untranslated
Blockly.Msg.VARIABLES_SET_TOOLTIP = "指定此變數和之後的值相等。";
Blockly.Msg.MATH_CHANGE_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.PROCEDURES_DEFRETURN_TITLE = Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE;
Blockly.Msg.CONTROLS_IF_IF_TITLE_IF = Blockly.Msg.CONTROLS_IF_MSG_IF;
Blockly.Msg.CONTROLS_WHILEUNTIL_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_MSG_THEN = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_ELSE_TITLE_ELSE = Blockly.Msg.CONTROLS_IF_MSG_ELSE;
Blockly.Msg.PROCEDURES_DEFRETURN_PROCEDURE = Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE;
Blockly.Msg.LISTS_GET_SUBLIST_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.LISTS_GET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.PROCEDURES_DEFRETURN_DO = Blockly.Msg.PROCEDURES_DEFNORETURN_DO;
Blockly.Msg.CONTROLS_IF_ELSEIF_TITLE_ELSEIF = Blockly.Msg.CONTROLS_IF_MSG_ELSEIF;
Blockly.Msg.LISTS_GET_INDEX_HELPURL = Blockly.Msg.LISTS_INDEX_OF_HELPURL;
Blockly.Msg.CONTROLS_FOREACH_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.LISTS_SET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.CONTROLS_FOR_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_FOR_INPUT_ORDER = "遞增計數迴圈";
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TITLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.TEXT_APPEND_VARIABLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.LISTS_INDEX_OF_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.PROCEDURES_DEFRETURN_COMMENT = Blockly.Msg.PROCEDURES_DEFNORETURN_COMMENT;

// Ardublockly strings
Blockly.Msg.ARD_ANALOGREAD = "類比輸入 腳位#";  // untranslated
Blockly.Msg.ARD_ANALOGREAD_TIP = "傳回選擇的類比腳位 0 到 1024 之間的值";  // untranslated
Blockly.Msg.ARD_ANALOGWRITE = "類比輸出 PWM腳位#";  // untranslated
Blockly.Msg.ARD_ANALOGWRITE_TIP = "輸出類比值 0 到 255 到指定 PWM 腳位";  // untranslated
Blockly.Msg.ARD_BUILTIN_LED = "數位輸出 內建LED ";  // untranslated
Blockly.Msg.ARD_BUILTIN_LED_TIP = "點亮或熄滅Arduino開發板內建的 LED";  // untranslated
Blockly.Msg.ARD_COMPONENT_WARN1 = "一個 %1 設置積木與 %2 相同名稱必須新增後才能使用此積木!";  // untranslated
Blockly.Msg.ARD_DEFINE = "定義";  // untranslated
Blockly.Msg.ARD_DIGITALREAD = "數位輸入 腳位#";  // untranslated
Blockly.Msg.ARD_DIGITALREAD_TIP = "在選擇的腳位讀取數位值是高(High)或低(Low)";  // untranslated
Blockly.Msg.ARD_DIGITALWRITE = "數位輸出 腳位#";  // untranslated
Blockly.Msg.ARD_DIGITALWRITE_TIP = "輸出數位值高(High)或低(Low)到指定腳位";  // untranslated
Blockly.Msg.ARD_FUN_RUN_LOOP = "迴圈程序: ";  // untranslated
Blockly.Msg.ARD_FUN_RUN_SETUP = "設定程序: ";  // untranslated
Blockly.Msg.ARD_FUN_RUN_TIP = "定義 Arduino 草稿碼的 setup() 和 loop() 程序.";  // untranslated
Blockly.Msg.ARD_HIGH = "高";  // untranslated
Blockly.Msg.ARD_HIGHLOW_TIP = "設定腳位的邏輯狀態是高(High)或低(Low).";  // untranslated
Blockly.Msg.ARD_LOW = "低";  // untranslated
Blockly.Msg.ARD_MAP = "對應";  // untranslated
Blockly.Msg.ARD_MAP_TIP = "重新對應 [0-1024]範圍值 到[0-其他範圍]的值.";  // untranslated
Blockly.Msg.ARD_MAP_VAL = "數值範圍到 [ 0 - ";  // untranslated
Blockly.Msg.ARD_NOTONE = "關閉音調 腳位#";  // untranslated
Blockly.Msg.ARD_NOTONE_PIN = "沒有音調 腳位#";  // untranslated
Blockly.Msg.ARD_NOTONE_PIN_TIP = "停止在選擇的腳位播放音調";  // untranslated
Blockly.Msg.ARD_NOTONE_TIP = "在選擇的腳位關閉音調";  // untranslated
Blockly.Msg.ARD_PIN_WARN1 = "腳位 %1 是必須的對於腳位 %2 如同腳位 %3. 已經使用腳位 %4.";  // untranslated
Blockly.Msg.ARD_PULSETIMEOUT_TIP = "量測選擇腳位產生高或低脈波的持續時間, 如果時間尚未過期(單位是微秒).";  // untranslated
Blockly.Msg.ARD_PULSE_READ = "量測 %1 脈波在腳位# %2";  // untranslated
Blockly.Msg.ARD_PULSE_READ_TIMEOUT = "量測 %1 脈波在腳位# %2 (過期時間: %3 微秒)";  // untranslated
Blockly.Msg.ARD_PULSE_TIP = "量測選擇腳位產生高或低脈波的持續時間.";  // untranslated
Blockly.Msg.ARD_SERIAL_BPS = "bps";  // untranslated
Blockly.Msg.ARD_SERIAL_PRINT = "顯示";  // untranslated
Blockly.Msg.ARD_SERIAL_PRINT_NEWLINE = "加上換行";  // untranslated
Blockly.Msg.ARD_SERIAL_PRINT_TIP = "顯示資料到 主控台/序列埠 這是可閱讀的 ASCII 字串.";  // untranslated
Blockly.Msg.ARD_SERIAL_PRINT_WARN = "設定serial區塊 %1 一定需要新增到工作區後才能使用此積木!";  // untranslated
Blockly.Msg.ARD_SERIAL_SETUP = "設定";  // untranslated
Blockly.Msg.ARD_SERIAL_SETUP_TIP = "選擇特定序列埠的傳輸率";  // untranslated
Blockly.Msg.ARD_SERIAL_SPEED = "傳輸率 :";  // untranslated
Blockly.Msg.ARD_SERVO_READ = "讀取 伺服馬達 腳位#";  // untranslated
Blockly.Msg.ARD_SERVO_READ_TIP = "讀取伺服馬達目前的角度";  // untranslated
Blockly.Msg.ARD_SERVO_WRITE = "設定 伺服馬達 腳位#";  // untranslated
Blockly.Msg.ARD_SERVO_WRITE_DEG_180 = "角度 (0~180)";  // untranslated
Blockly.Msg.ARD_SERVO_WRITE_TIP = "設定伺服馬達旋轉到指定角度";  // untranslated
Blockly.Msg.ARD_SERVO_WRITE_TO = "旋轉到";  // untranslated
Blockly.Msg.ARD_SETTONE = "播放音調 腳位#";  // untranslated
Blockly.Msg.ARD_SPI_SETUP = "設定";  // untranslated
Blockly.Msg.ARD_SPI_SETUP_CONF = "設置:";  // untranslated
Blockly.Msg.ARD_SPI_SETUP_DIVIDE = "通訊時脈";  // untranslated
Blockly.Msg.ARD_SPI_SETUP_LSBFIRST = "LSBFIRST";  // untranslated
Blockly.Msg.ARD_SPI_SETUP_MODE = "SPI 模式 (idle - edge)";  // untranslated
Blockly.Msg.ARD_SPI_SETUP_MODE0 = "0 (Low - Falling)";  // untranslated
Blockly.Msg.ARD_SPI_SETUP_MODE1 = "1 (Low - Rising)";  // untranslated
Blockly.Msg.ARD_SPI_SETUP_MODE2 = "2 (High - Falling)";  // untranslated
Blockly.Msg.ARD_SPI_SETUP_MODE3 = "3 (High - Rising)";  // untranslated
Blockly.Msg.ARD_SPI_SETUP_MSBFIRST = "MSBFIRST";  // untranslated
Blockly.Msg.ARD_SPI_SETUP_SHIFT = "位元順序";  // untranslated
Blockly.Msg.ARD_SPI_SETUP_TIP = "設置 SPI 周邊.";  // untranslated
Blockly.Msg.ARD_SPI_TRANSRETURN_TIP = "送出一個 SPI 訊息到特定的從端裝置, 和取得回傳資料.";  // untranslated
Blockly.Msg.ARD_SPI_TRANS_NONE = "none";  // untranslated
Blockly.Msg.ARD_SPI_TRANS_SLAVE = "到從端腳位#";  // untranslated
Blockly.Msg.ARD_SPI_TRANS_TIP = "送出一個 SPI 訊息到特定的從端裝置.";  // untranslated
Blockly.Msg.ARD_SPI_TRANS_VAL = "傳輸";  // untranslated
Blockly.Msg.ARD_SPI_TRANS_WARN1 = "設定SPI區塊 %1 一定需要新增到工作區後才能使用此積木!";  // untranslated
Blockly.Msg.ARD_SPI_TRANS_WARN2 = "舊腳位值 %1 已經不再可以使用.";  // untranslated
Blockly.Msg.ARD_STEPPER_COMPONENT = "步進馬達";  // untranslated
Blockly.Msg.ARD_STEPPER_DEFAULT_NAME = "MyStepper";  // untranslated
Blockly.Msg.ARD_STEPPER_FOUR_PINS = "4";  // untranslated
Blockly.Msg.ARD_STEPPER_MOTOR = ":";  // untranslated
Blockly.Msg.ARD_STEPPER_NUMBER_OF_PINS = "腳位數";  // untranslated
Blockly.Msg.ARD_STEPPER_PIN1 = "腳位1#";  // untranslated
Blockly.Msg.ARD_STEPPER_PIN2 = "腳位2#";  // untranslated
Blockly.Msg.ARD_STEPPER_PIN3 = "腳位3#";  // untranslated
Blockly.Msg.ARD_STEPPER_PIN4 = "腳位4#";  // untranslated
Blockly.Msg.ARD_STEPPER_REVOLVS = "每一圈有幾步";  // untranslated
Blockly.Msg.ARD_STEPPER_SETUP = "設置 步進馬達";  // untranslated
Blockly.Msg.ARD_STEPPER_SETUP_TIP = "設定步進馬達腳位和其他設定.";  // untranslated
Blockly.Msg.ARD_STEPPER_SPEED = "轉速(rpm)";  // untranslated
Blockly.Msg.ARD_STEPPER_STEP = "轉動 步進馬達";  // untranslated
Blockly.Msg.ARD_STEPPER_STEPS = "步";  // untranslated
Blockly.Msg.ARD_STEPPER_STEP_TIP = "旋轉步進馬達到設定的步數.";  // untranslated
Blockly.Msg.ARD_STEPPER_TWO_PINS = "2";  // untranslated
Blockly.Msg.ARD_TIME_DELAY = "等待";  // untranslated
Blockly.Msg.ARD_TIME_DELAY_MICROS = "微秒";  // untranslated
Blockly.Msg.ARD_TIME_DELAY_MICRO_TIP = "等待設定時間, 單位是微秒microseconds";  // untranslated
Blockly.Msg.ARD_TIME_DELAY_TIP = "等待設定時間, 單位是毫秒milliseconds";  // untranslated
Blockly.Msg.ARD_TIME_INF = "永遠等待 (直到程式結束)";  // untranslated
Blockly.Msg.ARD_TIME_INF_TIP = "等待直到程式結束執行.";  // untranslated
Blockly.Msg.ARD_TIME_MICROS = "執行經過的時間(微秒)";  // untranslated
Blockly.Msg.ARD_TIME_MICROS_TIP = "傳回Arduino開發板執行目前程式經過的時間, 單位是微秒microseconds. 傳回正的長整數";  // untranslated
Blockly.Msg.ARD_TIME_MILLIS = "執行經過的時間(毫秒)";  // untranslated
Blockly.Msg.ARD_TIME_MILLIS_TIP = "傳回Arduino開發板執行目前程式經過的時間, 單位是毫秒milliseconds. 傳回正的長整數";  // untranslated
Blockly.Msg.ARD_TIME_MS = "毫秒";  // untranslated
Blockly.Msg.ARD_TONEFREQ = "頻率";  // untranslated
Blockly.Msg.ARD_TONE_FREQ = "頻率";  // untranslated
Blockly.Msg.ARD_TONE_PIN = "播放音調 腳位#";  // untranslated
Blockly.Msg.ARD_TONE_PIN_TIP = "在選擇的腳位播放音調";  // untranslated
Blockly.Msg.ARD_TONE_TIP = "設定腳位產生頻率範圍 31 - 65535 的音調";  // untranslated
Blockly.Msg.ARD_TONE_WARNING = "頻率必須在範圍 31 - 65535";  // untranslated
Blockly.Msg.ARD_TYPE_ARRAY = "陣列";  // untranslated
Blockly.Msg.ARD_TYPE_BOOL = "布林";  // untranslated
Blockly.Msg.ARD_TYPE_CHAR = "字元";  // untranslated
Blockly.Msg.ARD_TYPE_CHILDBLOCKMISSING = "子積木遺失";  // untranslated
Blockly.Msg.ARD_TYPE_DECIMAL = "浮點數";  // untranslated
Blockly.Msg.ARD_TYPE_LONG = "長整數";  // untranslated
Blockly.Msg.ARD_TYPE_NULL = "空值";  // untranslated
Blockly.Msg.ARD_TYPE_NUMBER = "整數";  // untranslated
Blockly.Msg.ARD_TYPE_SHORT = "短整數";  // untranslated
Blockly.Msg.ARD_TYPE_TEXT = "字串";  // untranslated
Blockly.Msg.ARD_TYPE_UNDEF = "沒有定義";  // untranslated
Blockly.Msg.ARD_VAR_AS = "型態";  // untranslated
Blockly.Msg.ARD_VAR_AS_TIP = "型態轉換運算子, 設定值為指定的型態";  // untranslated
Blockly.Msg.ARD_WRITE_TO = "為";  // untranslated
Blockly.Msg.NEW_INSTANCE = "新實例...";  // untranslated
Blockly.Msg.NEW_INSTANCE_TITLE = "新實例名稱:";  // untranslated
Blockly.Msg.RENAME_INSTANCE = "重新命名實例...";  // untranslated
Blockly.Msg.RENAME_INSTANCE_TITLE = "重新命名所有 '%1' 實例為:";  // untranslated

// Enhanced Msgs
Blockly.Msg.ARD_SETTONEDURE="播放音調 腳位#";
Blockly.Msg.ARD_TONEDURE="持續時間";
Blockly.Msg.ARD_MAP2_VAL="值";
Blockly.Msg.ARD_MAP2_FromLow="從範圍: 低";
Blockly.Msg.ARD_MAP2_FromHigh="至高";
Blockly.Msg.ARD_MAP2_ToLow=" 到範圍: 低";
Blockly.Msg.ARD_MAP2_ToHigh="至高";
Blockly.Msg.ARD_MAP2_TIP="對應值從 [?-?] 範圍至 [?-?] 範圍.";

Blockly.Msg.ARD_CAR_L298N="設置 L298N 模組: ";
Blockly.Msg.ARD_CAR_L298N_TIP="定義 L298N 模組的腳位."
Blockly.Msg.ARD_CAR_Move="智慧車行走";
Blockly.Msg.ARD_CAR_Move_TIP="行走智慧車的程序";
Blockly.Msg.ARD_CAR_MOVE_WARN="設定積木 %1 必須在使用此積木前新增!";
Blockly.Msg.ARD_CAR_ULTRASOUND="設置 HC-SR04 超音波模組: ";
Blockly.Msg.ARD_CAR_ULTRASOUND_TIP="定義超音波模組的回應和觸發腳位.";
Blockly.Msg.ARD_CAR_ULTRASOUND_DISTANCE="超音波測量的距離";
Blockly.Msg.ARD_CAR_ULTRASOUND_DISTANCE_TIP="傳回超音波測量的距離";
Blockly.Msg.ARD_CAR_ULTRASOUND_Echo="回應腳位#";
Blockly.Msg.ARD_CAR_ULTRASOUND_Trigger="觸發腳位#"
Blockly.Msg.ARD_CAR_ULTRASOUND_DISTANCE_WARN="設定積木 %1 必須在使用此積木前新增!";
Blockly.Msg.ARD_CAR_MOVE_WARNING="PWM值的範圍必須是 0 - 255";

Blockly.Msg.ARD_SERIAL_AVAILABLE="有資料?";
Blockly.Msg.ARD_SERIAL_AVAILABLE_TIP="序列埠是否有資料?";
Blockly.Msg.ARD_SERIAL_READ="讀取位元組";
Blockly.Msg.ARD_SERIAL_READSTRING="是讀取字串";
Blockly.Msg.ARD_SERIAL_READ_TIP="序列埠讀取函數";
Blockly.Msg.ARD_SERIAL_PARSEINT="讀取整數";
Blockly.Msg.ARD_SERIAL_PARSEFLOAT="是讀取浮點數";
Blockly.Msg.ARD_SERIAL_PARSE_TIP="序列埠剖析數值函數";

Blockly.Msg.ARD_DIGITALPIN_TIP="Arduino數位腳位清單";
Blockly.Msg.ARD_ANALOGPIN_TIP="Arduino類比腳位清單";
Blockly.Msg.ARD_PWMPIN_TIP="Arduino PWM腳位清單";

Blockly.Msg.ARD_SOFTSERIAL_SETUP="SoftwareSerial 設定";
Blockly.Msg.ARD_SOFTSERIAL_SETUP_TIP="定義軟體序列埠的腳位";
Blockly.Msg.ARD_SOFTSERIAL_AVAILABLE="有資料?";
Blockly.Msg.ARD_SOFTSERIAL_AVAILABLE_TIP="軟體序列埠是否有資料";
Blockly.Msg.ARD_SOFTSERIAL_PRINT="SoftwareSerial 顯示";
Blockly.Msg.ARD_SOFTSERIAL_PRINT_TIP="軟體序列埠的輸出功能";
Blockly.Msg.ARD_SOFTSERIAL_READ="讀取位元組";
Blockly.Msg.ARD_SOFTSERIAL_READSTRING="是讀取字串";
Blockly.Msg.ARD_SOFTSERIAL_READ_TIP="軟體序列埠的讀取功能";

Blockly.Msg.VARIABLES_CONST="常數宣告 %1 變數 %2 指定初值為 %3";
Blockly.Msg.VARIABLES_CONST_HELPURL="https://github.com/google/blockly/wiki/Variables#declare";  // untranslated
Blockly.Msg.VARIABLES_CONST_TOOLTIP="宣告指定型態的常數變數且指定初值。";

Blockly.Msg.VARIABLES_INITIAL="宣告 %1 變數 %2 指定初值為 %3";
Blockly.Msg.VARIABLES_INITIAL_HELPURL="https://github.com/google/blockly/wiki/Variables#declare";  // untranslated
Blockly.Msg.VARIABLES_INITIAL_TOOLTIP="宣告指定型態的變數且指定初值。";

Blockly.Msg.MATH_INC_DECREMENT_EXP_TIP="遞增/遞減運算式。";
Blockly.Msg.ARD_VAR_AUTO_TYPE_TIP="指定敘述與算術的自動型態轉換。";

Blockly.Msg.TEXT_CHAR='http://arduino.cc/en/Reference/char';
Blockly.Msg.TEXT_CHAR_TOOLTIP='字元常數值, 只能是單一字元.';
Blockly.Msg.TEXT_CHAR_WARNING="只能指定單一字元值!";

Blockly.Msg.VARIABLES_CONST_WARNING="變數是常數, 不允許更改變數值!";

Blockly.Msg.TEXT_TOINT_HELPURL = "https://www.arduino.cc/reference/en/language/variables/data-types/string/functions/toint/";
Blockly.Msg.TEXT_TOINT_TITLE = "轉換 %1 成整數";
Blockly.Msg.TEXT_TOINT_TOOLTIP = "傳回字串轉換成的整數.";
Blockly.Msg.TEXT_TOFLOAT_HELPURL = "https://www.arduino.cc/reference/en/language/variables/data-types/string/functions/tofloat/";
Blockly.Msg.TEXT_TOFLOAT_TITLE = "轉換 %1 成浮點數";
Blockly.Msg.TEXT_TOFLOAT_TOOLTIP = "傳回字串轉換成的浮點數.";
